# deployment
host: 0.0.0.0 #localhost
port: 5001

sass:
  load_paths:
    - _sass
    - node_modules
    
include: [".htaccess", "node_modules"]
exclude: ["Gemfile", "Gemfile.lock", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
